language: d
matrix:
    allow_failures:
        - d: ldc
    include:
        - d: dmd
          env: USE_DOVERALLS=true
        - d: ldc

script:
    - chmod +x travis-script.sh
    - ./travis-script.sh
    - dub --single examples/list.d --compiler=${DC}
