// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'volumeinfo', kind: "module", path: './volumeinfo.html', attributes: []},
{name: 'volumeinfo.mountedVolumes', kind: "functiondeclaration", path: './volumeinfo/mountedVolumes.html', attributes: []},
{name: 'volumeinfo.VolumeInfo', kind: "structdeclaration", path: './volumeinfo/VolumeInfo.html', attributes: []},
{name: 'volumeinfo.VolumeInfo.bytesAvailable', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.bytesAvailable.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.bytesFree', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.bytesFree.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.bytesTotal', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.bytesTotal.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.device', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.device.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.isValid', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.isValid.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.label', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.label.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.path', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.path.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.readOnly', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.readOnly.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.ready', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.ready.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.VolumeInfo.refresh', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.refresh.html', attributes: ["nothrow", "trusted"]},
{name: 'volumeinfo.VolumeInfo.this', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.this.html', attributes: ["ref", "trusted"]},
{name: 'volumeinfo.VolumeInfo.type', kind: "functiondeclaration", path: './volumeinfo/VolumeInfo.type.html', attributes: ["nothrow", "property", "trusted"]},
{name: 'volumeinfo.volumePath', kind: "functiondeclaration", path: './volumeinfo/volumePath.html', attributes: ["trusted"]},
];
